---
- name: Create Helloworld App with CF Template
  cloudformation:
    stack_name: "{{vars['stacks']['helloworld']['stack-name']}}"
    state: present
    region: "{{vars['stacks']['helloworld']['region']}}"
    disable_rollback: True
    template: ../templates/{{vars['stacks']['helloworld']['templatefile']}}
    template_parameters:
      EnvironmentTag: "{{vars['stacks']['helloworld']['parameters']['EnvironmentTag']}}"
      OwnerTag: "{{vars['stacks']['helloworld']['parameters']['OwnerTag']}}"
      ALBName: "{{vars['stacks']['helloworld']['stack-name']}}-ALB"
      VPCCidrBlock: "{{vars['stacks']['helloworld']['parameters']['VPCCidrBlock']}}" 
      CodeDeployAppName: "{{vars['stacks']['helloworld']['parameters']['CodeDeployAppName']}}"
      CodeDeployS3Bucket: "{{vars['stacks']['helloworld']['parameters']['CodeDeployS3Bucket']}}"
      EC2AMI: "{{vars['stacks']['helloworld']['parameters']['EC2AMI']}}"
      EC2KeyPair: "{{vars['stacks']['helloworld']['parameters']['EC2KeyPair']}}"
      NotificationEmailAddress: "{{vars['stacks']['helloworld']['parameters']['NotificationEmailAddress']}}"
      NotificationTopicName: "{{vars['stacks']['helloworld']['parameters']['NotificationTopicName']}}"
      PeerVPCIdCidr: "{{vars['stacks']['helloworld']['parameters']['PeerVPCIdCidr']}}"
      NameTag: "{{vars['stacks']['helloworld']['parameters']['NameTag']}}"
    tags:
      Stack: "{{vars['stacks']['helloworld']['stack-name']}}"
  register: helloworld_stack
- name: Show Stack Outputs
  debug: msg="Stack outputs should be {{helloworld_stack.stack_outputs}}"