---
- name: Create Natgateway with CF Template
  cloudformation:
    stack_name: "{{stacks['natgateway']['stack-name']}}"
    state: present
    region: "{{stacks['natgateway']['region']}}"
    disable_rollback: True
    template: ../templates/subnets-template.json
    template_parameters:
      EnvironmentTag: "{{stacks['natgateway']['EnvironmentTag']}}"
      OwnerTag: "{{stacks['natgateway']['OwnerTag']}}"
      NatGateway1Name: "{{stacks['natgateway']['NatGateway1Name']}}"
      NatGateway2Name: "{{stacks['natgateway']['NatGateway2Name']}}"
    tags:
      Stack: "{{stacks['natgateway']['stack-name']}}NatGateway"
  register: natgateway_stack
- name: Show Stack Outputs
  debug: msg="Stack outputs should be {{natgateway_stack.stack_outputs}}"