---
- name: Create PeerConnection with CF Template
  cloudformation:
    stack_name: "{{vars['stacks']['peerconnection']['stack-name']}}"
    state: present
    region: "{{vars['stacks']['peerconnection']['region']}}"
    disable_rollback: True
    template: ../templates/{{vars['stacks']['peerconnection']['templatefile']}}
    template_parameters:
      EnvironmentTag: "{{vars['stacks']['peerconnection']['parameters']['EnvironmentTag']}}"
      OwnerTag: "{{vars['stacks']['peerconnection']['parameters']['OwnerTag']}}"
      InitialVpc: "{{vars['stacks']['peerconnection']['parameters']['InitialVpc']}}"
      InitialRouteTable: "{{vars['stacks']['peerconnection']['parameters']['InitialRouteTable']}}"
      DestinationCidrBlock: "{{vars['stacks']['peerconnection']['parameters']['DestinationCidrBlock']}}"
      ReverseDestinationCidrBlock: "{{vars['stacks']['peerconnection']['parameters']['ReverseDestinationCidrBlock']}}"
    tags:
      Stack: "{{vars['stacks']['peerconnection']['stack-name']}}"
  register: peer_stack
- name: Show Stack Outputs
  debug: msg="Stack outputs should be {{peer_stack.stack_outputs}}"