---
- name: Create Subnets with CF Template
  cloudformation:
    stack_name: "{{vars['stacks']['subnets']['stack-name']}}"
    state: present
    region: "{{vars['stacks']['subnets']['region']}}"
    disable_rollback: True
    template: ../templates/{{vars['stacks']['subnets']['templatefile']}}
    template_parameters:
      EnvironmentTag: "{{vars['stacks']['subnets']['parameters']['EnvironmentTag']}}"
      OwnerTag: "{{vars['stacks']['subnets']['parameters']['OwnerTag']}}"
      Nat1SubnetName: "{{vars['stacks']['subnets']['parameters']['Nat1SubnetName']}}"
      Nat1SubnetCidrBlock: "{{vars['stacks']['subnets']['parameters']['Nat1SubnetCidrBlock']}}"
      Nat2SubnetName: "{{vars['stacks']['subnets']['parameters']['Nat2SubnetName']}}"
      Nat2SubnetCidrBlock: "{{vars['stacks']['subnets']['parameters']['Nat2SubnetCidrBlock']}}"
      Web1SubnetName: "{{vars['stacks']['subnets']['parameters']['Web1SubnetName']}}"
      Web1SubnetCidrBlock: "{{vars['stacks']['subnets']['parameters']['Web1SubnetCidrBlock']}}"
      Web2SubnetName: "{{vars['stacks']['subnets']['parameters']['Web2SubnetName']}}"
      Web2SubnetCidrBlock: "{{vars['stacks']['subnets']['parameters']['Web2SubnetCidrBlock']}}"
      Util1SubnetName: "{{vars['stacks']['subnets']['parameters']['Util1SubnetName']}}"
      Util1SubnetCidrBlock: "{{vars['stacks']['subnets']['parameters']['Util1SubnetCidrBlock']}}"
      ALBSubnet1Name: "{{vars['stacks']['subnets']['parameters']['ALBSubnet1Name']}}"
      ALBSubnet1CidrBlock: "{{vars['stacks']['subnets']['parameters']['ALBSubnet1CidrBlock']}}"
      ALBSubnet2Name: "{{vars['stacks']['subnets']['parameters']['ALBSubnet2Name']}}"
      ALBSubnet2CidrBlock: "{{vars['stacks']['subnets']['parameters']['ALBSubnet2CidrBlock']}}"
    tags:
      Stack: "{{vars['stacks']['subnets']['stack-name']}}Subnets"
  register: subnet_stack
- name: Show Stack Outputs
  debug: msg="Stack outputs should be {{subnet_stack.stack_outputs}}"