---
- name: Create VPC with CF Template
  cloudformation:
    stack_name: "TEMP"
    state: present
    region: "us-east-2"
    disable_rollback: True
    template: ../templates/vpc.json
    template_parameters:
      EnvironmentTag: "TEMPTAG"
      VPCCidrBlock: "10.10.0.0/16"
      VPCName: "VPCNAME"
      OwnerTag: "jboynton"
    tags:
      Name: "Stack"
  register: vpc_stack
- name: Dump all vars
  action: template src=dumpall.j2 dest=/tmp/ansible.all
- name: Show Stack Outputs
  debug: msg="{{hostvars}}"
  debug: msg="Stack outputs should be {{vpc_stack.stack_outputs}}"
  debug: msg="This should be the value of the ID {{vpc_stack.stack_outputs['VPC']}}"